### ISSUE TITLE
error acc + dy does not match TauDEM

### ISSUE THREAD

**Issue by xxxlpj916** [HydrogeomorphologyTools/SedInConnect_2.3#3]
I have tried the exe and arcgis tool box, both of them showed that error accw.tif does not in the file system, I have tried several times and have no idea how to solve this problem

**Comment by HydrogeomorphologyTools** [comment]
Hi [xxxlpj916](https://github.com/xxxlpj916), this type of error is 99% related to TauDEM not working properly.
I suggest removing TauDEM and reinstalling it from the official page: https://github.com/dtarb/TauDEM/releases/download/v5.3.7/TauDEM537_setup.exe
The setup will automatically take care of installing MPI and GDAL dependencies. We also suggest (also here, in relation to TauDEM restrictions) using simple file path/names with no special characters and no spaces. As an example, you can put your raster files and SedInConnect exe into a folder like "C:\temp" and run SedInConnect with admin privileges in case your folders have restrictions.

**Comment by HydrogeomorphologyTools** [comment]
I don't know if you wrote us via e-mail with the error code attached here (you did not sign your issue here), in case, I reply also to the "_**dy does not match**_" error here below:

![picture](https://github.com/user-attachments/assets/3a564b5e-7aed-4b18-a28e-48c4dfdf59dd)

Thanks for using SedInConnect, we definitely suggest it over the ArcGIS toolbox.
The error you're experiencing is related to a TauDEM processing function raising the error.
As it's stated in the error message you have a mismatch in two values (249,931303 and 249,932500). I am assuming you probably have input files with non-square cell size, please check it and make it square for the tool to run properly. 
More details on the error here: 

The "dy does not match" error in TauDEM's PitRemove tool typically occurs when there is a mismatch in the grid spacing (cell size) of the input raster files. This can happen if the input Digital Elevation Model (DEM) has different cell sizes in the x and y directions.

Here are a few steps to troubleshoot and resolve this issue:

1.
Check Grid Spacing: Ensure that the input DEM has uniform grid spacing. You can use GIS software to inspect the cell size and make sure the x and y dimensions are equal.
2.
Reproject or Resample: If the grid spacing is not uniform, you may need to reproject or resample the DEM to have consistent cell sizes. Most GIS software, like QGIS or ArcGIS, can help with this.
3.
Verify Input Files: Double-check that all input files used in the PitRemove tool have the same projection and grid spacing.

Generally speaking, working with non-square pixel dx and dy seems to me a very bad practice, I suggest solution 2 i.e. reprojecting to a unique dy=dy size and possibly an integer value.

I report here also some further best practices we suggest when encountering "file does not exist" in the error:
I suggest removing TauDEM and reinstalling it from the official page: https://github.com/dtarb/TauDEM/releases/download/v5.3.7/TauDEM537_setup.exe
The setup will automatically take care of installing MPI and GDAL dependencies. We also suggest (also here, in relation to TauDEM restrictions) using simple file paths/names with no special characters and no spaces. As an example, you can put your raster files and SedInConnect exe into a folder like "C:\temp" and run SedInConnect with admin privileges in case your folders have restrictions.

These final suggestions are provided in case you have further troubles with the SW but IMO your main error is the first one, fix it like reported here and you should be good to go!


Take care,

Stefano

**Comment by NJK94** [comment]
Hello,

I had the same problem, where the command line replies with the error `dx does not match` and I would like to suggest a simple solution, that worked for me. 

The problem is caused by the sinkfilled DTM and the original DTM, that, if you checked _Use W_, you have to provide. The error message for my run was:

```
02/01/2025 23:27:42     opening dtmsca was successful!
This run may take on the order of 1 minutes to complete.
This estimate is very approximate.
Run time is highly uncertain as it depends on the complexity of the input data
and speed and memory of the computer. This estimate is based on our testing on
a ...
dx does not match: 2.500000 1.000000
area error 1
dx does not match: 2.500000 1.000000
area error 1
dx does not match: 2.500000 1.000000
area error 1
dx does not match: 2.500000 1.000000
area error 1
dx does not match: 2.500000 1.000000
area error 1
AreaDinf version 5.3.7
Input file C:/Users/.../Test2/DTMNoSinksang.tif has projected coordinate system.
Input file C:/Users/.../Test2/W.tif has projected coordinate system.
dx does not match: 2.500000 1.000000
area error 1
dx does not match: 2.500000 1.000000
area error 1

job aborted:
[ranks] message

[0] terminated

[1] process exited without calling finalize

[2-6] terminated

[7] process exited without calling finalize

---- error analysis -----

[1,7] on LAPTOP-
areadinf ended prematurely and may have crashed. exit code 0

---- error analysis -----
Traceback (most recent call last):
  File "<string>", line 2352, in OK_rw_conn_outlet
  File "<string>", line 1076, in CavalliConnectivityout
RuntimeError: `C:/Users/.../Test2/accW.tif' does not exist in the file system,
and is not recognised as a supported dataset name.
```

You can see, that there is a problem with different cell sizes (2.5 and 1.0). I am using SAGA GIS for my work and here it clearly states, that both DTMs have a cell zise of 2.5 [m]. 

If you have this problem, I suggest to check the meta data for the DTMs first, by using `gdalinfo` in the command line. Here you will see, if the meta data are the same or different. You should pay attention on the information such as `Coordinate system is`, `Origin` and `Pixel size`.  These showed totally different values what implies, that there might be a problem with the coordinate systems. In my case these are the different values:

```
C:\Users\...\Test2>gdalinfo DTMNoSinks.tif
Driver: GTiff/GeoTIFF
Files: DTMNoSinks.tif
Size is 3876, 4377
Coordinate System is `'
Origin = (626706.250001003030000,5173676.249878062900000)
Pixel Size = (2.500000000000000,-2.500000000000000)
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  626706.250, 5173676.250)
Lower Left  (  626706.250, 5162733.750)
Upper Right (  636396.250, 5173676.250)
Lower Right (  636396.250, 5162733.750)
Center      (  631551.250, 5168205.000)
Band 1 Block=3876x1 Type=Float32, ColorInterp=Gray
  Min=689.090 Max=3279.550
  Minimum=689.090, Maximum=3279.550, Mean=1831.785, StdDev=729.816
  NoData Value=-99999
  Metadata:
    STATISTICS_MAXIMUM=3279.5500488281
    STATISTICS_MEAN=1831.7850861423
    STATISTICS_MINIMUM=689.09002685547
    STATISTICS_STDDEV=729.81645923111

C:\Users\...\Test2>gdalinfo DigitalTerrainModel.tif
Driver: GTiff/GeoTIFF
Files: DigitalTerrainModel.tif
Size is 3876, 4377
Coordinate System is `'
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 4377.0)
Upper Right ( 3876.0,    0.0)
Lower Right ( 3876.0, 4377.0)
Center      ( 1938.0, 2188.5)
Band 1 Block=3876x256 Type=Float32, ColorInterp=Gray

C:\Users\nikol\Desktop\Test2>
```

As you see, there is a Pixel Size for the first DTM, but no such information for the second DTM. I think, that SedInConnect just assumes a Cell Size of 1.0 in that case.

The most simple solution is to set a coordinate system for the DTMs. In case of SAGA GIS you can do this with the tool under `Geoprossesing` -> `Projection` -> `Set Coordinate Reference System`. After doing so, SedInConnect has no more problems doing the calculation. 

I hope this comment provided some useful information and I wish everyone a succesfull work. 

Best regards,
Nikola Josef Kruck
